madchicken/homebridge-zigbee-nt

- package.json
- src/accessories/ikea/ikea-onoff-switch.ts
- src/accessories/ikea/ikea-tadfri-dim.ts
- src/accessories/xiaomi/temp-humi-sensor.ts
- src/accessories/zig-bee-accessory.ts
- src/index.ts
- src/platform.ts
- src/utils/promise-queue.ts
- src/zigbee/types.ts
- src/zigbee/zig-bee-client.ts
- src/zigbee/zigbee.ts
Refactoring of the code to allow more easy support for more devices.
Add Tadfri ON/OFF switch and Xiaomi temperature sensors (Fix #1 )
> [Improvement] Add Ikea On/OFF switch and Xiaomi temperature/humidity sensors

- config.schema.json
- package.json
- src/accessories/linkind/linkind-motion-sensor.ts
- src/index.ts
- src/platform.ts
- src/zigbee/types.ts
Fix pairing process #21 
Add multiple channels support
Add Linkind Motion sensor support
> [Release] Fix pairing and add more devices

- config.schema.json
- package.json
- src/accessories/zig-bee-accessory.ts
- src/index.ts
- src/platform.ts
- src/utils/find-serial-port.ts
- src/utils/promise-queue.ts
- src/utils/router-polling.ts
- src/zigbee/zig-bee-client.ts
Various fixes:
* Fix #25 - Map the right device
* Move ping to device and remove router poller
* Configure device when it comes online
> [Release] v1.0.3

- src/accessories/namron/namron-dimmer.ts
- src/accessories/namron/namron-switch.ts
- src/index.ts
Got 4512700 to work. Haven't tested the remaining, but should be the same for them as well.
> Namron 4512700, 1402755 and 4512704 support

- src/accessories/ikea/ikea-remote-switch.ts
- src/accessories/xiaomi/xiaomi-wireless-switch.ts
- src/index.ts
Added support for a possible variation on the 'lumi.sensor_ht.agl02' my sensor reported itself as 'lumi.sensor_ht' so I have added it here. All functions work as intended
> Added support for lumi.sensor_ht

- package.json
- yarn.lock
New supported  devices and bug fixing
> [Release] V1.0.5

- package.json
- src/accessories/zig-bee-accessory.ts
- src/zigbee/types.ts
- src/zigbee/zigbee.ts
- yarn.lock
* Upgrade dependencies
* Minor fixes
> [Release] V1.0.6

- src/accessories/innr/innr-white-temperature.ts
- src/accessories/innr/innr-white.ts
- src/accessories/philips/philips-hue-white-temperature.ts
- src/index.ts
Added just one innr model and one new model for Philips.
Should support more models but these two are the only ones i own and could therefore test.
> Add support for Philips bulbs with temperature and innr lights

- src/index.ts
added another PhilipsHueWhite identifier
> Update index.ts to support 'LWB010'

- package.json
- src/accessories/ikea/ikea-motion-sensor.ts
- src/accessories/ikea/ikea-onoff-switch.ts
- src/accessories/lonsonho/lonsonho-double-switch.ts
- src/accessories/xiaomi/leak-sensor.ts
- src/accessories/xiaomi/motion-sensor.ts
- src/accessories/xiaomi/vibration-sensor.ts
- src/accessories/zig-bee-accessory.ts
- src/builders/programmable-switch-service-builder.ts
- src/index.ts
- src/zigbee/types.ts
Round of improvements and bug fixes
> Improvements and bug fixes

- README.md
- package.json
- src/accessories/ikea/ikea-motion-sensor.ts
- src/accessories/ikea/ikea-onoff-switch.ts
- src/accessories/permit-join-accessory.ts
- src/accessories/touchlink-accessory.ts
- src/accessories/xiaomi/xiaomi-wireless-switch.ts
- src/accessories/zig-bee-accessory.ts
- src/index.ts
- src/platform.ts
- src/utils/router-polling.ts
- src/web/api/http-server.ts
- src/web/api/zigbee.ts
- src/web/ui/actions/devices.ts
- src/web/ui/components/devices/device-details-body.tsx
- src/web/ui/components/devices/device-details.tsx
- src/web/ui/components/devices/device-table.tsx
- src/zigbee/types.ts
- src/zigbee/zig-bee-client.ts
- src/zigbee/zigbee.ts
- tsconfig.json
- yarn.lock
* Fix devices configuration issues #62 #36
* Add Xiaomi WXKG11LM switch #58 
* Fix issue #60 (and update Readme)
* UI improvements
> Add new devices and fixes more bugs

- src/accessories/xiaomi/aqara-opple-switch.ts
> fixed wrong mapping of the switches

- src/accessories/xiaomi/aqara-opple-switch.ts
fixed the wrong mapping of the 6 button switch (4 real this time)
> Switches fix

- CHANGELOG.md
- src/index.ts
- Add Tuya Thermostat model TS0601 and manufacturer _TZE200_2dpplnsn
> Tuya Thermostat model TS0601 and manufacturer _TZE200_2dpplnsn

- src/accessories/configurable-accessory.ts
- src/builders/ambient-light-service-builder.ts
- src/builders/motion-sensor-service-builder.ts
Don't mess up with device state (Fix #141 )
> Fix reporting

- package.json
- src/accessories/configurable-accessory.ts
- src/accessories/gledopto/gledopto-dim.ts
- src/builders/__tests__/thermostat-service-builder.test.ts
- src/builders/thermostat-service-builder.ts
- src/zigbee/zig-bee-client.ts
- yarn.lock
Provide fixes for 
#141 
#140 
Fix some other minor things
> Bug fixing

- src/accessories/zig-bee-accessory.ts
Fix weird situation of missing configureKey for some accessory
> Fix configure error

- src/accessories/ikea/ikea-onoff-switch.ts
- src/accessories/ikea/ikea-remote-switch.ts
- src/accessories/ikea/ikea-shurtcut-switch.ts
- src/accessories/lonsonho/lonsonho-double-switch.ts
- src/accessories/xiaomi/aqara-opple-switch.ts
- src/zigbee/zig-bee-client.ts
Fix actions for Ikea buttons #154
> [Fix] Don't call super for ikea buttons

- package.json
- src/zigbee/zigBee-controller.ts
- yarn.lock
Upgrade internal dependencies to latest version
> Upgrade herdsman libraries

- package.json
- src/accessories/zig-bee-accessory.ts
- src/web/api/http-server.ts
- yarn.lock
Fix issue #203 (configure issue)
Fix issue #206 (configure issue)
Fix issue #204 (Logger problem)
> [Bug fixing] Fix various issues

- src/zigbee/zig-bee-client.ts
added function to write postion to device, function to get current he…ating setpoint and modified to use friendly names in error messages
> Add new functions to get/set device states

- src/zigbee/zig-bee-client.ts
Fix issue with logger in converters #221
> [Fix] Always add logger to meta information when using converters

- package.json
- yarn.lock
> [Fix] Blank UI

- src/accessories/zig-bee-accessory.ts
- src/zigbee/types.ts
> [Fix #242] Add logger to configure call
